name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0
    - name: Setup ionic environment
      run:  chown -R /usr/local/lib/node_modules && npm i ionic cordova -g
    - name:  Build ionic
      run: ionic cordova build android

      
      
