name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create ionic environment
      uses: ionic
    - name: Run ionic build
      run: ionic cordova build android
